name: continuous-integration/gh-actions/cli

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: update brew and install dependencies
      run: brew update && brew install openssl pkg-config boost hidapi zmq libpgm miniupnpc ldns expat libunwind-headers protobuf readline
    - name: build
      run: make -j3
    - name: Upload mac artifacts
      uses: actions/upload-artifact@master
      with:
        name: macos
        path: 'build/**/**/arqma*'

  build-windows:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: numworks/setup-msys2@v1
    - name: install ArQmA dependencies
      run: msys2do pacman -S --noconfirm autoconf automake-wrapper mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-protobuf-c mingw-w64-x86_64-libusb mingw-w64-x86_64-libtool mingw-w64-x86_64-gettext git
    - name: build
      run: msys2do make release-static-win
    - name: Upload windows artifacts
      uses: actions/upload-artifact@master
      with:
        name: windows
        path: 'build/**/**/arqma*'

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install ArQmA dependencies
      run: sudo apt -y install build-essential cmake libboost-all-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libnorm-dev libusb-1.0-0-dev libpgm-dev libprotobuf-dev protobuf-compiler gperf libreadline-dev
    - name: build
      run: make release -j2
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: linux
        path: 'build/**/**/arqma*'

  build-ubuntu-depends:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install ArQmA dependencies
      run: sudo apt -y install build-essential cmake libboost-all-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libnorm-dev libusb-1.0-0-dev libpgm-dev libprotobuf-dev protobuf-compiler gperf libreadline-dev
    - name: build
      run: make depends target=x86_64-linux-gnu -j2
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: linux-static
        path: 'build/x86_64-linux-gnu/release/bin/arqma*'

  build-ubuntu-dpends-compat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install ArQmA dependencies
      run: sudo apt -y install build-essential cmake libboost-all-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libnorm-dev libusb-1.0-0-dev libpgm-dev libprotobuf-dev protobuf-compiler gperf libreadline-dev
    - name: build
      run: make depends-compat target=x86_64-linux-gnu -j2
    - name: Upload linux artifacts
      uses: actions/upload-artifact@master
      with:
        name: linux-compat
        path: 'build/x86_64-linux-gnu-compat/release/bin/arqma*'
